<?php

namespace Tests\Unit\ApiFactory\Auth;

use App\Http\ApiFactory\Actions\Auth\RegisterAction;
use Dminustin\ApiFactory\Classes\ApiFactoryTestCase;
use Dminustin\ApiFactory\Exceptions\ClassNotFoundException;
use Dminustin\ApiFactory\Classes\ApiResponse;
use App\Http\ApiFactory\Actions\Auth\LoginAction;

/**
 * Class LoginActionTest
 * Generated by Laravel API Factory v.1.2.0.1
 */
class LoginActionTest extends ApiFactoryTestCase
{
    /**
     * @throws ClassNotFoundException
     */
    public function testAction()
    {
        $user = [
            'email' => '1@test.ru',
            'password' => 'test',
        ];
        $response = $this->getActionResponse(
            RegisterAction::class,
            array_merge($user, ['confirm' => 'yes'])
        );
        $this->assertInstanceOf(ApiResponse::class, $response);
        $this->assertTrue($response->result, 'Result is true');
        //do something


        $response = $this->getActionResponse(LoginAction::class, $user);
        $this->assertInstanceOf(ApiResponse::class, $response);
        $this->assertTrue($response->result, 'Result is true');
        //do something
    }
}
