<?php

namespace App\Http\ApiFactory\Controllers\Auth;

use Illuminate\Http\Request;
use Dminustin\ApiFactory\Classes\ApiFactoryController;

/**
 * Class LoginController
 * Generated by Laravel API Factory v.1.2.0.1
 */
class LoginController extends ApiFactoryController
{
    protected string $actionName = \App\Http\ApiFactory\Actions\Auth\LoginAction::class;

    //You may override handle() method
}