<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view(config('app.template') . '.welcome');
});
//GENERATED BY Laravel API Factory
Route::post('/api/v1auth/login', [App\Http\ApiFactory\Controllers\Auth\LoginController::class, 'handle'])->middleware(['guest']);
Route::post('/api/v1auth/register', [App\Http\ApiFactory\Controllers\Auth\RegisterController::class, 'handle'])->middleware(['guest']);
Route::post('/api/v1auth/reset', [App\Http\ApiFactory\Controllers\Auth\ResetController::class, 'handle'])->middleware(['guest']);
Route::post('/api/v1tags/add', [App\Http\ApiFactory\Controllers\Tags\AddController::class, 'handle'])->middleware(['user']);
