<?php

namespace App\Http\ApiFactory\Actions\Auth;

use Dminustin\ApiFactory\Classes\ApiFactoryAction;
use Dminustin\ApiFactory\Classes\ApiResponse;
use Dminustin\LSNE\CorePackage\Models\User;
use Illuminate\Support\Facades\Hash;

/**
 * Class LoginAction
 * Generated by Laravel API Factory v.1.2.0.1
 */
class LoginAction extends ApiFactoryAction
{
    protected array $validationRules = [
        'email'=>'email|required',
        'password'=>'string|required',
    ];

    public function handle(): ApiResponse
    {
        $user = User::query()->where('email','=', $this->data['email'])->first();
        if(!$user) {
            throw new \Exception('User not found');
        }
        if (!Hash::check($this->data['password'], $user->password)) {
            throw new \Exception('User not found');
        }
        $this->response->setData($user->toArray())->setResult(true);
        return $this->response;
    }
}
