<?php

namespace App\Http\ApiFactory\Actions\Auth;

use Dminustin\ApiFactory\Classes\ApiFactoryAction;
use Dminustin\ApiFactory\Classes\ApiResponse;
use Dminustin\LSNE\CorePackage\Models\User;
use Illuminate\Support\Facades\Hash;

/**
 * Class RegisterAction
 * Generated by Laravel API Factory v.1.2.0.1
 */
class RegisterAction extends ApiFactoryAction
{
    protected array $validationRules = [
        'email'=>'email|required|unique:users',
        'password'=>'string|required',
        'confirm'=>'string|required',
    ];

    public function handle(): ApiResponse
    {
        //do something with $this-data
        $user = new User();
        $user->email = $this->data['email'];
        $user->name = $this->data['email'];
        $user->password = Hash::make($this->data['password']);
        $user->save();
        $this->response->setData($user->toArray())->setResult(true);
        return $this->response;
    }
}
