<?php

namespace App\Http\ApiFactory\Actions\Auth;

use Dminustin\ApiFactory\Classes\ApiFactoryAction;
use Dminustin\ApiFactory\Classes\ApiResponse;

/**
 * Class ResetAction
 * Generated by Laravel API Factory v.1.2.0.1
 */
class ResetAction extends ApiFactoryAction
{
    protected array $validationRules = [
        'email'=>'string|required',
    ];

    public function handle(): ApiResponse
    {
        $this->response->setResult(true);
        return $this->response;
    }
}
