<?php

namespace App\Http\ApiFactory\Actions\Tags;

use Dminustin\ApiFactory\Classes\ApiFactoryAction;
use Dminustin\ApiFactory\Classes\ApiResponse;

/**
 * Class AddAction
 * Generated by Laravel API Factory v.1.2.0.1
 */
class AddAction extends ApiFactoryAction
{
    protected array $validationRules = [
        'tag'=>'string|required',
        'object_id'=>'string|required',
        'object_type'=>'string|required',
    ];

    public function handle(): ApiResponse
    {
        //do something with $this-data
        return $this->response;
    }
}