<?php

namespace App\Http\ApiFactory\Controllers\Tags;

use Illuminate\Http\Request;
use Dminustin\ApiFactory\Classes\ApiFactoryController;

/**
 * Class AddController
 * Generated by Laravel API Factory v.1.2.0.1
 */
class AddController extends ApiFactoryController
{
    protected string $actionName = \App\Http\ApiFactory\Actions\Tags\AddAction::class;

    //You may override handle() method
}